version: '3.9'

services:
  postgres:
    image: postgis/postgis:14-3.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=gps123
      - POSTGRES_USER=dev
      - POSTGRES_DB=psqldb-gps-emulator
    command:
      - postgres
      - -c
      - shared_buffers=256MB
      - -c
      - max_connections=200

volumes:
  postgres_data:
